config/routes.rb
Rails.application.routes.draw do
  root "chatroom#index"

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
    scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimun: 3, maximum: 15}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def current_user
    return @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    return !!current_user
  end

  def require_user
    if ! logged_in?
      flash[:error] = "Você tem que estar logado para fazer isso"
      redirect_to login_path 
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController  < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display #funcao esta em models/message.rb
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", msg: message_render(message)
    end
  end

  private
  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message} )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "Logado com Sucesso"
      redirect_to root_path
    else
      flash.now[:error] = "Dados incorretos ou Conta não existe, tente novamente"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Deslogado com Sucesso"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "Você já está logado!"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned medium icon header">
  <i class="circular red chat icon"></i>
  Diga Algo
</h2>

<div class="ui two column grid">
    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content" id="messages-box">
                <div class="ui feed" id="message-container">
                    <%= render @messages %>
                </div>
            </div>
            <div class="extra content">
              <%= form_for(@message, html: {class: "ui reply form", role: "form"},  url: message_path, remote: true ) do |f| %>
                <div class="field">
                  <div class="ui fluid icon input">
                    <%= f.text_field :body %>
                    <%= f.button '<i class="bordered inverted red edit icon"></i>'.html_safe %>
                  </div>
                </div>
              <% end %>
            </div>
        </div> 
    </div>

    <div class="four wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content">
                <div class="ui inverted vertical menu">
                <a class="active item">
                    Felipe
                </a>
                <a class="item">
                    Gustavo
                </a>
                <a class="item">
                    Paulo
                </a>
                </div>
            </div>
        </div>
    </div>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_body|%>
  <div class="ui <%= message_type %> message container transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_type.upcase %>
    </div>
    <p><%= message_body %></p>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui small inverted menu">

  <div class="ui container">
    <%= link_to 'BatePapo', root_path, class: "item" %>
    <%= link_to 'Mensagens', root_path, class: "item" %>

    <div class="right menu">
      <div class="ui dropdown item">
        Conta <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to 'Sair', logout_path, method: :delete, class: "item"%>
          <% else %>
            <%= link_to 'Fazer Login', login_path, class: "item"%>
          <% end %>
        </div>
      </div>

      <% if !logged_in? %>
        <div class="item">
          <%= link_to 'Fazer Login', login_path, class: "ui red button" %>
        </div>
      <% end %>

    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages'%>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
    <div class="summary">
        <Strong><%= message.user.username %></Strong>: <%= message.body %>
    </div>
    </div>
</div>